-- MySQL Script generated by MySQL Workbench
-- Mon Mar 27 17:44:55 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tutorial
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tutorial
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tutorial` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tutorial` ;

-- -----------------------------------------------------
-- Table `tutorial`.`tipocliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`tipocliente` (
  `i_tipocliente_tipocliente` INT NOT NULL AUTO_INCREMENT,
  `s_sctipocliente_tipocliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`i_tipocliente_tipocliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tutorial`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tutorial`.`cliente` (
  `i_id_cliente` INT NOT NULL AUTO_INCREMENT,
  `s_nome_cliente` VARCHAR(50) NOT NULL,
  `i_cpf_cliente` CHAR(11) NOT NULL,
  `s_endereco_cliente` VARCHAR(100) NULL DEFAULT NULL,
  `s_telefone_cliente` CHAR(11) NULL DEFAULT NULL,
  `i_tipo_cliente` INT NOT NULL DEFAULT '1',
  PRIMARY KEY (`i_id_cliente`),
  INDEX `fk_tipocliente` (`i_tipo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tipocliente`
    FOREIGN KEY (`i_tipo_cliente`)
    REFERENCES `tutorial`.`tipocliente` (`i_tipocliente_tipocliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
